name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:  # Menambahkan pemicu manual

defaults:
  run:
    shell: bash

jobs:
  ios:
    name: iOS

    runs-on: macos-13

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: build
          key: ios-cmake-v2

      - name: Configure
        run: |
          cmake \
            -B build \
            -D CMAKE_TOOLCHAIN_FILE=cmake/toolchain/ios.toolchain.cmake \
            -D ENABLE_BITCODE=0 \
            -D PLATFORM=OS64 \
            -G Xcode \
            -D CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY='' \
            # EOL

      - name: Build
        run: |
          cmake \
            --build build \
            --config RelWithDebInfo \
            -j $(sysctl -n hw.physicalcpu) \
            # EOL

      - name: Pack
        run: |
          cd build
          cpack -C RelWithDebInfo

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fallout2-ce.ipa
          path:  build/fallout2-ce.ipa
          retention-days: 7